# Welcome to NumPy 

In [2]:
import numpy as np

In [4]:
np.array

<function numpy.core.multiarray.array>

In [23]:
#One dimentional
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
#two Dimensional array

b=np.array([[1,2],[3,4],[4,5],[5,600]])
print(b)
print("Three Index value is",b[3])

[ 1  2  3  4  5  6  7  8  9 10]
[[  1   2]
 [  3   4]
 [  4   5]
 [  5 600]]
Three Index value is [  5 600]


In [18]:
# minimum dimensions
c= np.array([1,2,3,4,5],ndmin=32)
print(c)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [21]:
# dtype parameter
d = np.array([1,2,3,4,5],dtype=complex)
print(d)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [3]:
#Using array-scalar type
dt=np.dtype(np.int64)
print(dt)

int64


In [36]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
dt=np.dtype('i8')
print(dt)

dt=np.dtype('>i4')
print(dt)

int64
>i4


In [46]:
# first create structured data type
dt=np.dtype([('Age',np.int8)])
print(dt)
a=np.array([(10),(20),(30,)],dtype=dt)
print(type(a))
print(a)
print(a['Age'])

[('Age', 'i1')]
<class 'numpy.ndarray'>
[(10,) (20,) (30,)]
[10 20 30]


In [52]:
student = np.dtype([('Name','S20'),('age','i1'),('marks','f4')])
print(student[1])
print(student)

a=np.array([('abc',21,50),('xyz',18,75)],dtype=student)
print(a)

int8
[('Name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [59]:
a=np.array([[1,2,3],[4,5,60]])
print("Display the row and column of the matrix",a.shape)
print(a)
a.shape=(3,2)
print(a)
      

Display the row and column of the matrix (2, 3)
[[ 1  2  3]
 [ 4  5 60]]
[[ 1  2]
 [ 3  4]
 [ 5 60]]


In [74]:
a=np.arange(24)
print(a)
print(a[10])
print(a[19])

print(a.ndim)

#now reshape it
b=a.reshape(4,2,3)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
10
19
1
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [78]:
# dtype of array is int8(1 byte)
x= np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)
# nUmpy flags 
print(x.flags)
x = np.array([1,2,3,4,5], dtype=np.float32) 
print(x.itemsize) 

1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
4


In [3]:
# Empty Array 

a = np.empty([3,5],dtype=int)
print(a)

[[        0         0         0         0         0]
 [        0         0         0         0         0]
 [     1212         0         0 929327460         0]]


In [6]:
b =np.array()

In [99]:
# zeros 
x=np.zeros(4)
print(x)

x=np.zeros((5,),dtype=np.int8)
print(x)

x=np.zeros((3,4),dtype=np.int8)
print(x)

x=np.zeros((3,4),dtype=[('x','i4'),('y','i4')])
print(x)

[0. 0. 0. 0.]
[0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[(0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0)]]


In [103]:
# ones 
x=np.ones(7,dtype=np.int8)
print(x)

y=np.zeros((3,4),dtype=np.int8)
print(y)

[1 1 1 1 1 1 1]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [105]:
# convert list ton ndarray

x=[1,2,3,4,5]
a=np.asarray(x)
print(a)

x=[1,2,3,4,5]
a=np.asarray(x,dtype=float)
print(a)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [107]:
# ndarray from tuple 
import numpy as np 
x = (1,2,3) 
a = np.asarray(x) 
print(a) 

# two dimension

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a) 

[1 2 3]
[(1, 2, 3) (4, 5)]


In [111]:
list = range(7)
print(list)

# obtain iterator object from list 
it = iter(list)

x=np.fromiter(it,dtype=float)
print(x)

range(0, 7)
[0. 1. 2. 3. 4. 5. 6.]


In [116]:
v=np.arange(24,dtype=float)
print(v)

x=np.arange(10,20,2)
print("Two Step each",x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
Two Step each [10 12 14 16 18]


In [5]:
myarr = np.array([1,2,3,4,5],dtype=np.int32)
print(myarr)
print(myarr[4])
myarr[3]=709
print(myarr)
myarr.size

[1 2 3 4 5]
5
[  1   2   3 709   5]


5

In [9]:
#linespace
lspace = np.linspace(1,5,12)
print(lspace)


[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [12]:
emp = np.empty((4,5))
print(emp)
emplike = np.empty_like(lspace)
print("This empty_like ",emplike)


[[1.         1.21052632 1.42105263 1.63157895 1.84210526]
 [2.05263158 2.26315789 2.47368421 2.68421053 2.89473684]
 [3.10526316 3.31578947 3.52631579 3.73684211 3.94736842]
 [4.15789474 4.36842105 4.57894737 4.78947368 5.        ]]
This empty_like  [1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [16]:
# For Identity Matrix
ide = np.identity(4) # 4 x 4 matrix
print(ide)
print("Shape is ",ide.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape is  (4, 4)


In [20]:
list2 = [[12,23,56,67],[23,45,75,23]]
print(list2)
print(type(list2))
tuple2 = ((2,3,5,6,6),(3,56,3,2,4))
print(tuple2)
print(type(tuple2))

[[12, 23, 56, 67], [23, 45, 75, 23]]
<class 'list'>
((2, 3, 5, 6, 6), (3, 56, 3, 2, 4))
<class 'tuple'>


In [22]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Sum of first , second and third column respetively

In [26]:
ar.sum(axis=0)

array([12, 15, 18])

In [27]:
ar.sum(axis=1) # for Row wise sum 

array([ 6, 15, 24])

In [31]:
#tranpose Of array arr for use of capital T
print(ar.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
ar.flat

In [33]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [35]:
# show number of element 
print(ar.size)

9


In [37]:
# Number of bytes consume
ar.nbytes

36

In [39]:
#Index of maximum value
one = np.array([1,2,3,4,56,4])
p=one.argmax()
print(p)

#index of Minimum value
m=one.argmin()
print(m)

4
0


In [42]:
#Soring index of array
print(one.argsort())

[0 1 2 3 5 4]


In [50]:
print(ar)
print(type(ar))

ar

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
ar.argmax()

8

In [59]:
print(ar.argmin())
# print maximum number index 
print(ar.argmax(axis=0))
print(ar.argmax(axis=1))
print(ar.argsort(axis=1))

0
[2 2 2]
[2 2 2]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [62]:
ar=ar.reshape(9,1)
print(ar)
ar=ar.ravel()
print(ar)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [73]:
#Adding Two Array 
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
print(ar2)
ar=ar.reshape(3,3)
print(ar)
arr3=ar + ar2
print(arr3)


[[1 2 1]
 [4 0 6]
 [8 1 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  4]
 [ 8  5 12]
 [15  9  9]]


In [74]:
arr3= ar*ar2
print(arr3)

[[ 1  4  3]
 [16  0 36]
 [56  8  0]]


In [75]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [76]:
ar.sum()

45

In [77]:
ar.max()

9

In [78]:
ar.min()

1

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [81]:
type(np.where(ar>5))

tuple

In [82]:
np.count_nonzero(ar)

9

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [84]:
ar[1,2]=0

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [86]:
import sys

In [87]:
py_ar = [0,4,55,2]

In [88]:
np_arr = np.array(py_ar)

In [89]:
sys.getsizeof(1) * len(py_ar)

112

In [92]:
np_arr.itemsize * np_arr.size

16

In [94]:
np_arr.tolist()

[0, 4, 55, 2]