In [1]:
import numpy as np
import cv2

In [2]:
np.__version__

'1.14.3'

In [3]:
cv2.__version__

'3.4.1'

In [4]:
dir(cv2.ml)

['ANN_MLP_ANNEAL',
 'ANN_MLP_BACKPROP',
 'ANN_MLP_GAUSSIAN',
 'ANN_MLP_IDENTITY',
 'ANN_MLP_LEAKYRELU',
 'ANN_MLP_NO_INPUT_SCALE',
 'ANN_MLP_NO_OUTPUT_SCALE',
 'ANN_MLP_RELU',
 'ANN_MLP_RPROP',
 'ANN_MLP_SIGMOID_SYM',
 'ANN_MLP_UPDATE_WEIGHTS',
 'ANN_MLP_create',
 'ANN_MLP_load',
 'BOOST_DISCRETE',
 'BOOST_GENTLE',
 'BOOST_LOGIT',
 'BOOST_REAL',
 'Boost_DISCRETE',
 'Boost_GENTLE',
 'Boost_LOGIT',
 'Boost_REAL',
 'Boost_create',
 'Boost_load',
 'COL_SAMPLE',
 'DTREES_PREDICT_AUTO',
 'DTREES_PREDICT_MASK',
 'DTREES_PREDICT_MAX_VOTE',
 'DTREES_PREDICT_SUM',
 'DTrees_PREDICT_AUTO',
 'DTrees_PREDICT_MASK',
 'DTrees_PREDICT_MAX_VOTE',
 'DTrees_PREDICT_SUM',
 'DTrees_create',
 'DTrees_load',
 'EM_COV_MAT_DEFAULT',
 'EM_COV_MAT_DIAGONAL',
 'EM_COV_MAT_GENERIC',
 'EM_COV_MAT_SPHERICAL',
 'EM_DEFAULT_MAX_ITERS',
 'EM_DEFAULT_NCLUSTERS',
 'EM_START_AUTO_STEP',
 'EM_START_E_STEP',
 'EM_START_M_STEP',
 'EM_create',
 'EM_load',
 'KNEAREST_BRUTE_FORCE',
 'KNEAREST_KDTREE',
 'KNearest_BRUTE_FORCE',
 '

In [7]:
a = 5
print(type(a))
int_list = list(range(10))
print(int_list)

<class 'int'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
i=0
str_list = [str(i) for i in int_list]
print(str_list)
print(type(i))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'int'>


In [10]:
int_list * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
int_array = np.array(int_list)
print(int_array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print("int arr ndim :",int_array.ndim)
print("int_arr shape:",int_array.shape)
print("int_arr size:",int_array.size)
print("int_arr dtype",int_array.dtype)

int arr ndim : 1
int_arr shape: (10,)
int_arr size: 10
int_arr dtype int32


In [28]:
print(int_array)
print(int_array[0])
print(int_array[-1])


[0 1 2 3 4 5 6 7 8 9]
0
9


In [34]:
# Slicing Arrays
print(int_array[2:5])
print(int_array[:5])
print(int_array[5:])
print(int_array[:])
print(int_array[::2])
print(int_array[::-1])

[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [38]:
arr_2d = np.zeros((3,5))
print(arr_2d)

arr_float_3d = np.ones((3,2,4)) 
print(arr_float_3d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [46]:
arr_float_3d[0,:,:]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
aa= np.ones((3,3))
aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
arr_uint_3d = np.ones((3,2,4),dtype = np.uint8) * 255
arr_uint_3d

array([[[255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

In [68]:
from sklearn import datasets
from sklearn import metrics 
from sklearn import model_selection as model
from sklearn import linear_model
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [69]:
boston = datasets.load_boston()

In [70]:
dir(boston)

['DESCR', 'data', 'feature_names', 'target']

In [71]:
boston.data.shape

(506, 13)

In [74]:
boston.target.shape

(506,)

In [80]:
linear = linear_model.LinearRegression()
x_train,x_test,y_train,y_test = model.train_test_split(boston.data,boston.target,test_size=0.1,random_state=42)

In [84]:
linear.fit(x_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [85]:
metrics.mean_squared_error(y_train,linear.predict(x_train))

22.73948415423661

In [86]:
linear.score(x_train,y_train)

0.7374934091901197

In [3]:
ret, frame = [1,2,3] , [7,8,9]
print(ret)
print(frame)

[1, 2, 3]
[7, 8, 9]


In [14]:
a = np.array([[1,2,3],[4,5,6]],dtype = 'float')
print(a)

list:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
d = np.full((3,3),6,dtype='complex')
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [18]:
#create Array with random value
d = np.random.random((4,3))
print(d)

[[0.7347225  0.91871712 0.01276072]
 [0.6559604  0.30029757 0.23490863]
 [0.99643543 0.27962574 0.5497106 ]
 [0.04749547 0.19246616 0.33622311]]


In [20]:
# create a sequence of integer
# from 0 to 30
f =np.arange(0,30,2)
print(f)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [21]:
#Create sequence of 10 values in range 0 to 5
g = np.linspace(0,5,10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [24]:
#Reshaping 3x4 array to 2*2*3 array
arr = np.array([[1,2,3,4],
               [5,2,4,2],
               [1,2,0,1]])
#print(arr)
newarr= arr.reshape(2,2,3)
print(newarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [25]:
#Flatten Array
arr = np.array([[1,2,3],[4,5,6]])
flarr = arr.flatten()
print(arr)
print(flarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [31]:
arr = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2.0]])

print(arr,"\n")
#Slicing
temp = arr[:2,::2]
print(temp)


[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]] 

[[-1.  0.]
 [ 4.  6.]]


In [38]:
arr = np.array([1,2,3,4]) *12
print(arr * 2)

[24 48 72 96]


In [45]:
# squaring
arr = np.array([1,2,3,4]) **3
print(arr)


[ 1  8 27 64]


In [51]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

print(arr.max())
print("Row Wise maximum",arr.max(axis=1))
print(arr.min())
print(arr.sum())
print(arr.cumsum(axis = 1))

9
Row Wise maximum [6 7 9]
1
38
[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [56]:
arr = np.array([1,2,3])
arr2= np.array([4,5,6])
a = arr+arr2
print(arr+arr2,a)


[5 7 9]
