In [1]:
import numpy as np
myarray=np.array([[1,2,3,],[4,5,6]])
print(myarray)


[[1 2 3]
 [4 5 6]]


In [17]:
print(myarray.reshape(1,6))

[[1 2 3 4 5 6]]


In [18]:
zero_mat=np.zeros([6,4],dtype=int)
print(zero_mat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
one_mat=np.ones([4,4],dtype=int)
print(one_mat)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [21]:
arr2=np.append(arr,[4,7])
print(arr2)

b = np.array(12,dtype=int)
for i in range(10):
    np.append(b,i)
    
    
    
print(b)

[1 2 3 4 7]
12


In [22]:
arr3=np.delete(arr,1)
print(arr3)

[1 3]


In [23]:
arr4=np.concatenate((arr,np.array([3,4])),axis=0)
print(arr4)

[1 2 3 3 4]


In [24]:
#Slice items in numpy
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [25]:
print(a[2:5])

[2 3 4]


In [26]:
a2=np.array([[1,2,3],[3,4,5],[4,5,6],[9,6,7]])
print(a2)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [9 6 7]]


In [27]:
print(a2[:3])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [28]:
print(a2[2:])

[[4 5 6]
 [9 6 7]]


In [13]:
b = []
c = 0
fac=[121,234,456,123,672,785]
for i in fac:
    c=int(i/10)
    b.append(c)
    print(c)
    

    
print(b)
 

12
23
45
12
67
78
[12, 23, 45, 12, 67, 78]


In [8]:
n=12
print(n)
#print(n%10)

n=n*n
print(n)


12
144
