In [1]:
import cv2
import numpy as np

In [ ]:
# Image Airthementic
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('Orignal',img)

m=np.ones(img.shape,dtype="uint8") * 150
print(m)
print(img) 

added = cv2.add(img,m)
cv2.imshow('Added',added)

subt= cv2.subtract(img,m)
cv2.imshow('Subtract',subt)

mul=cv2.multiply(img,m)
cv2.imshow('Mulplay',mul)

cv2.imwrite('E:\openCvImage\Addition image.jpg',added)
cv2.imwrite('E:\openCvImage\Subtraction image.jpg',subt)
cv2.imwrite('E:\openCvImage\Multiplay image.jpg',mul)


cv2.waitKey(0)
cv2.destroyAllWindows()

[[[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 ...

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]]
[[[ 93  94  92]
  [105 107 107]
  [103 105 106]
  ...
  [ 97 110  96]
  [100 116  99]
  [100 118 101]]

 [[125 127 121]
  [140 141 137]
  [135 136 134]
  ...
  [112 125 109]
  [111 127 110]
  [109 127 110]]

 [[124 127 112]
  [141 143 131]
  [130 134 123]
  ...
  [108 124 106]
  [104 123 104]
  [ 99 118  99]]

 ...

 [[ 79  65  42]
  [ 91  75  52]
  [ 91  75  52]
  ..

In [2]:
square = np.zeros((300,300),np.uint8)
print(square)
#rectangle(img,startingPoint,endPoint,color,thinksness)
cv2.rectangle(square,(50,50),(250,250),255,-1)
cv2.imshow('Square',square)

#Making As Ellipse

ellipse = np.zeros((300,300),np.uint8)
cv2.ellipse(ellipse, (150,150),(150,150),30,0,180,255,-1)
cv2.imshow('Ellipse',ellipse)

# And Operation

And = cv2.bitwise_and(square,ellipse)
cv2.imshow("And",And)

#Or operation

Or=cv2.bitwise_or(square,ellipse)
cv2.imshow('Or',Or)
# XOR Operation
xor=cv2.bitwise_xor(square,ellipse)
cv2.imshow('Xor',xor)
# NOt opeartion
Not=cv2.bitwise_not(square)
cv2.imshow('Not',Not)

cv2.imwrite('E:\openCvImage\And image.jpg',And)
cv2.imwrite('E:\openCvImage\Or Image.jpg',Or)
cv2.imwrite('E:\openCvImage\XOR image.jpg',xor)



cv2.waitKey()

cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
# Image Blurring
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('Orignal Image',img)

# Creating 3X3 Kernal

kernal_3x3 = np.ones((3,3),np.float32)/9

#We use the cv2.filter2D to convole the kernal with on image
blurred = cv2.filter2D(img,-1,kernal_3x3)
cv2.imshow('3x3 kernal Blurring',blurred)
print(blurred)

#creating 7X7 Kernal
kernal_7x7 = np.ones((7,7),np.float)/49
blurred2=cv2.filter2D(img,-1,kernal_3x3)
cv2.imshow('7X7 Kernal Blurring',blurred2)

cv2.imwrite('E:\openCvImage\Blurring3X3 image.jpg',blurred)
cv2.imwrite('E:\openCvImage\Blurring7X7 Image.jpg',blurred2)

cv2.waitKey()
cv2.destroyAllWindows()

[[[124 125 122]
  [122 124 121]
  [124 125 124]
  ...
  [107 120 105]
  [107 122 106]
  [107 124 107]]

 [[124 126 119]
  [122 124 118]
  [124 126 122]
  ...
  [106 120 103]
  [104 121 104]
  [104 122 104]]

 [[144 145 133]
  [140 142 131]
  [143 145 135]
  ...
  [111 126 108]
  [108 125 107]
  [107 125 106]]

 ...

 [[ 88  73  50]
  [ 88  73  50]
  [ 93  76  53]
  ...
  [165 187 160]
  [162 184 157]
  [164 185 159]]

 [[ 86  71  48]
  [ 86  71  48]
  [ 91  75  52]
  ...
  [167 188 162]
  [167 188 163]
  [170 191 166]]

 [[ 87  72  49]
  [ 87  72  49]
  [ 92  76  53]
  ...
  [169 190 165]
  [172 192 168]
  [175 196 172]]]


In [5]:
# Image Edge detection

img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg',0)
height,width =img.shape

#Extract slop edges
soble_x= cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
soble_y= cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)

cv2.imshow('Orignal Image',img)

cv2.imshow('Sobel_x image',soble_x)
cv2.imshow('Sobel_y image',soble_y)

soble_or = cv2.bitwise_or(soble_x,soble_y)
cv2.imshow('Soble or Image',soble_or)

laplacian= cv2.Laplacian(img,cv2.CV_64F)
cv2.imshow('Laplacian Image',laplacian)

canny=cv2.Canny(img,20,170)
cv2.imshow('Canny Edge',canny)

cv2.imwrite('E:\openCvImage\Soble_x image.jpg',soble_x)
cv2.imwrite('E:\openCvImage\Soble_y Image.jpg',soble_y)
cv2.imwrite('E:\openCvImage\soble_or image.jpg',soble_or)
cv2.imwrite('E:\openCvImage\Laplacian image.jpg',laplacian)
cv2.imwrite('E:\openCvImage\Canny Image.jpg',canny)

cv2.waitKey(0)
cv2.destroyAllWindows()

