In [1]:
import cv2
import numpy as np

In [5]:

#Hue : 0 - 180
#Saturation : 0 - 255
#value : 0 - 255

img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('origan image',img)

img_HSV = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV Iimage',img_HSV)
cv2.imshow('Hue Channel ',img_HSV[:,:,0])
cv2.imshow('Saturation Channel ',img_HSV[:,:,1])
cv2.imshow('Value Channel ',img_HSV[:,:,2])

cv2.imwrite('E:\openCvImage\HSV image.jpg',img_HSV)
cv2.imwrite('E:\openCvImage\Hue image.jpg',img_HSV[:,:,0])
cv2.imwrite('E:\openCvImage\Saturation image.jpg',img_HSV[:,:,1])
cv2.imwrite('E:\openCvImage\Value image.jpg',img_HSV[:,:,2])


cv2.waitKey(0)
cv2.destroyAllWindows()


In [6]:
#RGB Image 


img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('origan image',img)



B,G,R = cv2.split(img)
zeros = np.zeros(img.shape[:2] ,dtype="uint8")

cv2.imshow("RED",cv2.merge([zeros,zeros,R]))


cv2.imshow("Green",cv2.merge([zeros,G,zeros]))


cv2.imshow("Blue",cv2.merge([B,zeros,zeros]))


cv2.imshow("Blue Green ",cv2.merge([B,G,zeros]))


cv2.imshow("Blue Red",cv2.merge([B,zeros,R]))
cv2.waitKey(0)

cv2.imwrite('E:\openCvImage\Origan Image.jpg',img)
cv2.imwrite('E:\openCvImage\RED.jpg',cv2.merge([zeros,zeros,R]))
cv2.imwrite('E:\openCvImage\Green image.jpg',cv2.merge([zeros,G,zeros]))
cv2.imwrite('E:\openCvImage\Blue image.jpg',cv2.merge([B,zeros,zeros]))
cv2.imwrite('E:\openCvImage\Blue Green image.jpg',cv2.merge([B,G,zeros]))
cv2.imwrite('E:\openCvImage\Blue Red.jpg',cv2.merge([B,zeros,R]))
cv2.imwrite('E:\openCvImage\Bile image.jpg',cv2.merge([zeros,G,R]))

cv2.destroyAllWindows()

In [2]:
print("Hello")

Hello


In [2]:
# Image Translation 
img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('Orignal Image',img)
#  Store height and width of the image
height,width = img.shape[:2]
print(height)
print(width)

quarter_height ,quarter_width = height/4 ,width/4
print(quarter_height)
print(quarter_width)

#     [1 0 Tx]
# T =[o  1 Ty]

# T is Our Translation Matrix
T = np.float32([[1,0,quarter_width],
               [0,1,quarter_height]])

print(T)

# We use warpAffine Transformation to shift the image
img_translation = cv2.warpAffine(img, T,(width,height))

cv2.imshow('Tranlation Image',img_translation)

#Save the image
cv2.imwrite('E:\openCvImage\Translation Image.jpg',img_translation)
cv2.waitKey(0)
cv2.destroyAllWindows()

340
860
85.0
215.0
[[  1.   0. 215.]
 [  0.   1.  85.]]


In [3]:
# Image Rotation

img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')

height,width = img.shape[:2]
rotation_matrix = cv2.getRotationMatrix2D((width/2,height/2),120,.3)
rotated_image =cv2.warpAffine(img,rotation_matrix,(width,height))

cv2.imshow('Origal image',img)
cv2.imshow('Roteted Image',rotated_image)
cv2.imwrite('E:\openCvImage\Rotation Image.jpg',rotated_image)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [4]:
# Image Transpose
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')

rotated_img = cv2.transpose(img)

roo=cv2.transpose(rotated_img)

cv2.imshow('orignal Image',img)
cv2.imshow('Rotated Image',rotated_img)
cv2.imshow("Last Image ",roo)
cv2.imwrite('E:\openCvImage\Rotated Image.jpg',rotated_img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
#Scaling or resizing and interplotation
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('orignal Image',img)

#Let's mok the size of our image 3/4 of it's orignal size
img_scaled = cv2.resize(img,None,fx=0.75,fy=0.75)
cv2.imshow('Scaling - Linear Interplotation',img_scaled)

#Let's doubled the size of our image
img_double=cv2.resize(img,None,fx=1.5,fy=1.5,interpolation=cv2.INTER_CUBIC)
cv2.imshow('Scaling - cubic Interpolation image ',img_double)

#Let's skew the re-sizing by setting exact dimensions/user define dimension
img_skew=cv2.resize(img,(900,400),interpolation=cv2.INTER_AREA)
cv2.imshow('Skew Image',img_skew)

# save all the image
cv2.imwrite('E:\openCvImage\Scaling - Linear  Image.jpg',img_scaled)
cv2.imwrite('E:\openCvImage\Scaling - Cubic  Image.jpg',img_double)
cv2.imwrite('E:\openCvImage\Scaling - Skew Image.jpg',img_skew)



cv2.waitKey()
cv2.destroyAllWindows()



In [5]:
#Image resizing using pyrmid
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')


smaller=cv2.pyrDown(img)
larger=cv2.pyrUp(img)


cv2.imshow('orignal Image',img)
cv2.imshow('smaller image',smaller)
cv2.imshow('larger image',larger)

# save all the image
cv2.imwrite('E:\openCvImage\Smaller Image.jpg',smaller)
cv2.imwrite('E:\openCvImage\larger Image.jpg',larger)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# image cropping

img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')

height,width = img.shape[:2]

#Let's get the starting pixel coordinate(top left,of cropping rectangle)
start_row,start_col = int(height*.25),int(width*.25)

#let's get the ending pixel coodinate (bottom right)
end_row,end_col = int(height*.75),int(width*.75)
#Simply use the indexing to crop the image

cropped =img[start_row:end_row,start_col:end_col]

cv2.imshow('orignal Image',img)
cv2.imshow('Cropped Image',cropped)

cv2.imwrite('E:\openCvImage\cropped Image.jpg',cropped)


cv2.waitKey(0)
cv2.destroyAllWindows()


In [8]:
# image Arithmetic

img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('orignal Image',img)

M=np.ones(img.shape,dtype="uint8") * 150
print(M)


cv2.waitKey(0)
cv2.destroyAllWindows()


[[[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 ...

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]]


In [5]:
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('Orignal Image',img)

# Creating 3X3 Kernal

kernal_3x3 = np.ones((3,3),np.float32)/9

#We use the cv2.filter2D to convole the kernal with on image
blurred = cv2.filter2D(img,-1,kernal_3x3)
cv2.imshow('3x3 kernal Blurring',blurred)


#creating 7X7 Kernal
kernal_7x7 = np.ones((7,7),np.float)/49
blurred2=cv2.filter2D(img,-1,kernal_3x3)
cv2.imshow('7X7 Kernal Blurring',blurred2)

cv2.imwrite('E:\openCvImage\Blurring3X3 image.jpg',blurred)
cv2.imwrite('E:\openCvImage\Blurring7X7 Image.jpg',blurred2)
print(blurred)
cv2.waitKey()
cv2.destroyAllWindows()

[[[124 125 122]
  [122 124 121]
  [124 125 124]
  ...
  [107 120 105]
  [107 122 106]
  [107 124 107]]

 [[124 126 119]
  [122 124 118]
  [124 126 122]
  ...
  [106 120 103]
  [104 121 104]
  [104 122 104]]

 [[144 145 133]
  [140 142 131]
  [143 145 135]
  ...
  [111 126 108]
  [108 125 107]
  [107 125 106]]

 ...

 [[ 88  73  50]
  [ 88  73  50]
  [ 93  76  53]
  ...
  [165 187 160]
  [162 184 157]
  [164 185 159]]

 [[ 86  71  48]
  [ 86  71  48]
  [ 91  75  52]
  ...
  [167 188 162]
  [167 188 163]
  [170 191 166]]

 [[ 87  72  49]
  [ 87  72  49]
  [ 92  76  53]
  ...
  [169 190 165]
  [172 192 168]
  [175 196 172]]]
