In [1]:
import cv2 
import numpy as np

In [4]:
cv2.__version__

'3.4.1'

# Reading Image

In [2]:
img = cv2.imread('E:\OpenCvImage\lena_color.jpg')
cv2.imshow("Output Image",img)

cv2.imwrite('E:\OpenCvImage\Leena.jpg',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Information


In [9]:
print(img.shape)
# This shape function show Height,width and leyer (R,G,B)
print("Height of image in pixel ",img.shape[0])
print("width of image in pixel",img.shape[1])
print("Leyer of image ",img.shape[2])
print(img[100,100,0])
print(img.size)
print(img.dtype)


(512, 512, 3)
Height of image in pixel  512
width of image in pixel 512
Leyer of image  3
91
786432
uint8


# Convert into GrayScale

In [10]:
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Scale Image is",gray_img)
print(gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[161 163 163 ... 169 153 125]
 [161 163 162 ... 171 155 125]
 [162 163 162 ... 171 154 122]
 ...
 [ 28  26  38 ...  97  94  93]
 [ 28  27  42 ...  99  93 103]
 [ 30  27  42 ...  98 100 102]]


# Concert Into Binary Image

In [13]:
ret ,bw=cv2.threshold(gray_img,127,255,cv2.THRESH_BINARY)
cv2.imshow("Binary Image is ",bw)
print(bw)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255   0]
 [255 255 255 ... 255 255   0]
 [255 255 255 ... 255 255   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [15]:
#Hue : 0 - 180
#Saturation : 0 - 255
#Value : 0 -255

img = cv2.imread('D:\Photos\saved Pictures\slider11.jpg')
cv2.imshow("Output is ",img)

img_hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow("HSV image is ",img_hsv)
cv2.imshow("Hue chennal ",img_hsv[:,:,0])
cv2.imshow("Saturation Chennal",img_hsv[:,:,1])
cv2.imshow("Value Chennal  ",img_hsv[:,:,2])

cv2.waitKey(0)
cv2.destroyAllWindows()

# RGB IMAGE

In [3]:
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
print(img[:])
cv2.imshow("Origibal Image",img)
B,G,R = cv2.split(img)
img
zeros = np.zeros(img.shape[:2],dtype="uint8")
print(zeros)
cv2.imshow("RED",cv2.merge([zeros,zeros,R]))
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 93  94  92]
  [105 107 107]
  [103 105 106]
  ...
  [ 97 110  96]
  [100 116  99]
  [100 118 101]]

 [[125 127 121]
  [140 141 137]
  [135 136 134]
  ...
  [112 125 109]
  [111 127 110]
  [109 127 110]]

 [[124 127 112]
  [141 143 131]
  [130 134 123]
  ...
  [108 124 106]
  [104 123 104]
  [ 99 118  99]]

 ...

 [[ 79  65  42]
  [ 91  75  52]
  [ 91  75  52]
  ...
  [172 194 166]
  [172 193 168]
  [153 175 147]]

 [[ 82  68  45]
  [ 93  77  54]
  [ 94  78  55]
  ...
  [179 200 175]
  [186 207 182]
  [173 194 169]]

 [[ 78  64  41]
  [ 85  71  48]
  [ 85  69  46]
  ...
  [143 164 139]
  [163 183 160]
  [162 182 159]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Making Image Using array

In [4]:
img = np.zeros((3,3),dtype=np.uint8)
print(img)

img = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
print(img)
print(img.shape)
cv2.imshow("Origranl Image ",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [18]:
import os
randomByteArray = bytearray(os.urandom(120000))
#print(randomByteArray)
flatNumberArray = np.array(randomByteArray)
print(flatNumberArray)
# convert the array to make a 400*300 grayscale image
grayimage = flatNumberArray.reshape(300,400)
cv2.imshow("Random Image",grayimage)

#Converting the array to make a 400*100 color image
bgrimage = flatNumberArray.reshape(100,400,3)
print(bgrimage)
cv2.imshow("Random Color Image",bgrimage)

cv2.waitKey(0)
cv2.destroyAllWindows()

[ 81  82 218 ...  44  50 220]
[[[ 81  82 218]
  [ 97 203  43]
  [ 23  57 183]
  ...
  [143 105 179]
  [ 19 130 193]
  [ 72 201 213]]

 [[ 22  55  99]
  [127  20 121]
  [187  35  93]
  ...
  [ 82 129  36]
  [107 203 114]
  [175 234 138]]

 [[ 57  40 100]
  [113 150 195]
  [108 249 169]
  ...
  [ 34  32  24]
  [ 54 253  93]
  [ 41 223 158]]

 ...

 [[163 233  43]
  [157 162  40]
  [216 231 143]
  ...
  [161 156 142]
  [ 77 164 202]
  [152  29 138]]

 [[145 124  46]
  [200 183  48]
  [244  38 154]
  ...
  [240 225 100]
  [ 71  41  70]
  [249 232  22]]

 [[ 62 153 214]
  [  0  26 158]
  [220 213  42]
  ...
  [220 219 112]
  [240   8 202]
  [ 44  50 220]]]


In [17]:
img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow("Origran Image",img)
B,G,R = cv2.split(img)
print(img.shape)
print(img.shape[:2])
zeros = np.zeros(img.shape[:2],dtype="uint8")
print(zeros)

cv2.imshow("RED",cv2.merge([zeros,zeros,R]))

cv2.imshow("Green",cv2.merge([B,zeros,zeros]))
cv2.imshow("Blue",cv2.merge([zeros,G,zeros]))
cv2.imshow("Blue Green ",cv2.merge([B,G,zeros]))
cv2.imshow("RED,blue and green ",cv2.merge([B,G,R]))


cv2.imshow("Blue Red",cv2.merge([B,zeros,R]))
cv2.waitKey(0)
cv2.destroyAllWindows()

(340, 860, 3)
(340, 860)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow("Origran Image",img)

height,width = img.shape[:2]
print(height,width)

quarter_height, quarter_width = height/4 , width/4
print(quarter_height,quarter_width)

#     [1 0 Tx]
# T =[o  1 Ty]

# T is Our Translation Matrix
T = np.float32([[1,0,quarter_width],
              [0,1,quarter_height]])

print(T)

img_translation = cv2.warpAffine(img,T,(width,height))

cv2.imshow("Translation Image",img_translation)

cv2.waitKey(0)
cv2.destroyAllWindows()

340 860
85.0 215.0
[[  1.   0. 215.]
 [  0.   1.  85.]]


In [6]:
# Image Rotation
img = cv2.imread('E:\OpenCvImage\lena_color.jpg')
cv2.imshow("Orignal Image",img)

height,width = img.shape[:2]
rotation_matrix = cv2.getRotationMatrix2D((width/4,height/4),120,.3)
rotated_image = cv2.warpAffine(img,rotation_matrix,(width,height))

cv2.imshow('Origal image',img)
cv2.imshow('Roteted Image',rotated_image)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# Image Transpose
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')

rotated_img = cv2.transpose(img)

cv2.imshow('orignal Image',img)
cv2.imshow('Rotated Image',rotated_img)

cv2.imwrite('E:\openCvImage\Rotated Image.jpg',rotated_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Resize Image

In [3]:
img=cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow('orignal Image',img)
# Linear Interploatation
img_scaled = cv2.resize(img,None,fx=0.75,fy=0.75)
cv2.imshow("Scalling Linear Interplotation",img_scaled)
# Cubic interplotataion
img_scaled1 = cv2.resize(img,None,fx=2,fy=2,interpolation=cv2.INTER_CUBIC)
cv2.imshow("scaling Cubic Interploatation",img_scaled1)

#Let's skew the re-sizing by setting exact dimensions/user define dimension
img_skew=cv2.resize(img,(900,400),interpolation=cv2.INTER_AREA)
cv2.imshow('Skew Image',img_skew)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
smaller = cv2.pyrDown(img)
large = cv2.pyrUp(img)
cv2.imshow("Smallerv image ",smaller)
cv2.imshow("Large Image ",large)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#Image cropping
img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow("Orignal Image",img)
print(img.shape)
height, width = img.shape[:2]
print(height)
print(width)
#Let's get the starting pixel coordinate(top left,of cropping rectangle)
start_row,start_col = int(height*.25),int(width*.25)
print(start_row)
print(start_col)

#let's get the ending pixel coodinate (bottom right)
end_row,end_col = int(height*.75),int(width*.75)
print(end_row)
print(end_col)

# Simply use the indexing to crop the image
cropped = img[start_row:end_row,start_col:end_col]

cv2.imshow("Cropped Image",cropped)

cv2.waitKey(0)
cv2.destroyAllWindows()

(340, 860, 3)
340
860
85
215
255
645


# Image Arthemetic 

In [11]:
img = cv2.imread('D:\Photos\Saved Pictures\slider11.jpg')
cv2.imshow("Original Image",img)
print(img.shape)
print(img[1][2])

m=np.ones(img.shape,dtype="uint8") * 150
print(m)
added = cv2.add(img,m)
cv2.imshow("Added ",added)

subtract = cv2.subtract(img,m)
cv2.imshow("Subtract",subtract)

mulplay = cv2.multiply(img,m)
cv2.imshow("Multiplication ",mulplay)
    
cv2.waitKey()
cv2.destroyAllWindows()

(340, 860, 3)
[135 136 134]
[[[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 ...

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]

 [[150 150 150]
  [150 150 150]
  [150 150 150]
  ...
  [150 150 150]
  [150 150 150]
  [150 150 150]]]


In [13]:
square = np.zeros((300,300),np.uint8)
print(square)
#rectangle(img,startingPoint,endPoint,color,thinksness)
cv2.rectangle(square,(50,50),(250,250),255,-1)
cv2.imshow('Square',square)

ellips = np.zeros((300,300),np.uint8)
cv2.ellipse(ellips,(150,150),(150,150),30,0,180,255,-1)
cv2.imshow("Ellipse",ellips)

And = cv2.bitwise_and(square,ellips)
cv2.imshow("And Image",And)

OR = cv2.bitwise_or(square,ellips)
cv2.imshow("And Image",OR)

XOR = cv2.bitwise_xor(square,ellips)
cv2.imshow("And Image",XOR)

NOT = cv2.bitwise_not(square)
cv2.imshow("And Image",NOT)


cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Image Blurring


In [10]:
cv2.imshow("Original Image",img)
# creating 3 x 3 kernal
# We use the cv2.filter2D to convert the kernal with on image
kernal_3x3 = np.ones((3,3),np.float32)/9

blurred = cv2.filter2D(img,-1,kernal_3x3)
cv2.imshow("3x3 kernal Image ",blurred)

# creating 3 x 3 kernal
# We use the cv2.filter2D to convert the kernal with on image
kernal_7x7 = np.ones((7,7),np.float32)/49

blurred2 = cv2.filter2D(img,-1,kernal_7x7)
cv2.imshow("7x7 kernal Image ",blurred2)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Blurring Using other technique

In [6]:
cv2.imshow("Original Image",img)

blur = cv2.blur(img,(7,7))
cv2.imshow("Blur Image",blur)

#Insted of using Box filter use gaussinan kernel

Gaussian = cv2.GaussianBlur(img,(7,7),0)
cv2.imshow("Gaussian Blur ",Gaussian)

#Take median of all the pixels under kernel area and central
#element is replaced with this median value

#median = cv2.medianBlur(img,5)
#cv2.imshow("Median Blur Image",median)

#Bilateral is very effective in nose removal
#bilateral = cv2.bilaterlFilter(img,9,75,75)
#cv2.imshow('Bilateral Blur Image',bilateral)

cv2.waitKey(0)
cv2.destroyAllWindows()