In [15]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB


In [41]:
data = pd.read_csv("spambase.data").as_matrix()

np.random.shuffle(data)
np.random.seed(seed=101)

x_train = data[:-100,:-2]
y_train = data[:-100,-1:]

x_test = data[-100:,:-2]
y_test = data[-100:,-1:]

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [42]:
data

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 2.900e+01, 8.800e+01,
        0.000e+00],
       [3.200e-01, 0.000e+00, 8.000e-01, ..., 1.500e+01, 1.590e+02,
        1.000e+00],
       [0.000e+00, 0.000e+00, 5.800e-01, ..., 1.300e+01, 1.460e+02,
        0.000e+00],
       ...,
       [4.900e-01, 3.200e-01, 4.600e-01, ..., 1.930e+02, 3.269e+03,
        1.000e+00],
       [0.000e+00, 0.000e+00, 1.920e+00, ..., 6.000e+00, 1.700e+01,
        1.000e+00],
       [1.700e-01, 0.000e+00, 8.000e-02, ..., 4.800e+01, 5.750e+02,
        1.000e+00]])

In [43]:
y_test

array([[0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],

In [44]:
y_test.size

100

In [45]:
x_test

array([[0.000e+00, 0.000e+00, 9.400e-01, ..., 0.000e+00, 1.766e+00,
        4.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.333e+00,
        3.000e+00],
       [0.000e+00, 5.400e-01, 0.000e+00, ..., 0.000e+00, 1.325e+00,
        5.000e+00],
       ...,
       [4.900e-01, 3.200e-01, 4.600e-01, ..., 1.650e-01, 6.896e+00,
        1.930e+02],
       [0.000e+00, 0.000e+00, 1.920e+00, ..., 0.000e+00, 1.416e+00,
        6.000e+00],
       [1.700e-01, 0.000e+00, 8.000e-02, ..., 0.000e+00, 4.049e+00,
        4.800e+01]])

In [46]:
spam_detector = MultinomialNB()

In [47]:
spam_detector.fit(x_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [48]:
print("prediction :",spam_detector.score(x_test,y_test))

prediction : 0.8


In [49]:
from sklearn.externals import joblib

In [50]:
joblib.dump(spam_detector,"spam_detector.pk1")

['spam_detector.pk1']