In [1]:
import tensorflow as tf

C:\Users\hp\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'2.0.0'

In [3]:
tf.compat.v1.disable_eager_execution()
hello = tf.constant('Hello, TensorFlow!')

sess = tf.compat.v1.Session()

print(sess.run(hello))

b'Hello, TensorFlow!'


In [4]:
tf.compat.v1.disable_eager_execution()
hello = tf.constant("Hello  Gaurav Kumar")
world = tf.constant("My name is Gaurav Kumar")

print(hello)
print(type(hello))

Tensor("Const_1:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


In [5]:
sess = tf.compat.v1.Session()
print(sess.run(hello))

b'Hello  Gaurav Kumar'


In [6]:
with tf.compat.v1.Session() as sess:
    result = sess.run(hello+world)

In [7]:
print(result)

b'Hello  Gaurav KumarMy name is Gaurav Kumar'


In [8]:
tf.compat.v1.disable_eager_execution()

In [9]:
a = tf.constant(10)
b = tf.constant(20)
c = tf.add(a,b)


sess = tf.compat.v1.Session()
print("Sum is ",sess.run(c))

Sum is  30


# Matrix

In [10]:
mat_1 = tf.fill((5,5),10)
mat_1

<tf.Tensor 'Fill:0' shape=(5, 5) dtype=int32>

In [11]:
zeros = tf.zeros((5,5))

In [12]:
ones = tf.ones((5,5))

In [13]:
sess = tf.compat.v1.Session()
print(sess.run(ones))
print("matrix",sess.run(mat_1))
print("Zeros ",sess.run(zeros))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
matrix [[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
Zeros  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
myops = [ones,mat_1,zeros]

In [15]:
sess2 = tf.compat.v1.InteractiveSession()

In [16]:
for op in myops:
    print(sess2.run(op))
    print("\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




# another why

In [17]:
for op in myops:
    print(op.eval())
    print("\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]




In [18]:
a1 = tf.constant([[1,2],[3,4]])

In [19]:
a1.get_shape()

TensorShape([2, 2])

In [20]:
b1 = tf.constant([[10,100],[9,9]])

In [21]:
b1.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_6:0' shape=(2, 2) dtype=int32>>

In [22]:
result = tf.matmul(a1,b1)

In [23]:
sess2.run(result)

array([[ 28, 118],
       [ 66, 336]])

# TensorFlow graphs

In [24]:
var1 = tf.constant(10)
var2 = tf.constant(20)
var3 = tf.constant(0)

var3=var2+var1

In [25]:
sess3 = tf.compat.v1.Session()

In [26]:
with tf.compat.v1.Session() as sess3:
    result = sess3.run(var3)

In [27]:
print(result)

30


In [28]:
print(var3)

Tensor("add_2:0", shape=(), dtype=int32)


In [29]:
print(tf.compat.v1.get_default_graph())

In [30]:
g = tf.compat.v1.Graph()
print(g)

In [31]:
g_1 = tf.compat.v1.get_default_graph()
print(g_1)

In [32]:
g_2 = tf.compat.v1.Graph()
print(g_2)

In [33]:
with g_2.as_default():
    print(g_2 is tf.compat.v1.get_default_graph())
    

True


# Creation of Variables 

# Execrise 3 

In [39]:
sess = tf.compat.v1.InteractiveSession()

C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [40]:
ss= tf.compat.v1.Session()

In [41]:
my_tensor = tf.compat.v1.random_uniform((5,5),0,2)

In [42]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(5, 5) dtype=float32>

In [43]:
c1 = tf.compat.v1.Variable(initial_value=my_tensor)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [44]:
print(c1)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32>


In [46]:
init = tf.compat.v1.global_variables_initializer()

In [47]:
sess.run(init)

In [48]:
sess.run(c1)

array([[0.09193063, 1.4874158 , 1.7123556 , 0.38281393, 1.203861  ],
       [0.3092959 , 1.4912827 , 0.25771594, 1.8318751 , 1.7655118 ],
       [1.4264526 , 1.1924775 , 1.0474169 , 0.43403292, 0.8741474 ],
       [0.42592573, 0.47141743, 1.9635968 , 0.27912807, 0.32311296],
       [1.0324132 , 0.70463324, 0.17588472, 0.15537977, 1.1822114 ]],
      dtype=float32)

# Creation of  Placeholder

In [54]:
ph = tf.compat.v1.placeholder(tf.float32)

In [55]:
ph2 = tf.compat.v1.placeholder(tf.float32,shape=(None,4))